# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'xtreamiptvplayerreactnative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
     pod 'KSYMediaPlayer_iOS'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end

